import { createClient } from '@/lib/supabase/server'
import { notFound } from 'next/navigation'
import Link from 'next/link'

export const dynamic = 'force-dynamic'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ArrowLeft, Share2, Download, TrendingUp, TrendingDown, Minus, CheckCircle } from 'lucide-react'

const reportTypeLabels: Record<string, string> = {
  'weekly-sales': 'Weekly Sales',
  'monthly-finance': 'Monthly Finance',
  'team-performance': 'Team Performance',
  'custom': 'Custom',
}

function TrendIcon({ trend }: { trend: string }) {
  if (trend === 'up') return <TrendingUp size={16} className="text-green-500" />
  if (trend === 'down') return <TrendingDown size={16} className="text-red-500" />
  return <Minus size={16} className="text-muted-foreground" />
}

export default async function ReportViewPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const supabase = await createClient()

  const { data: report, error } = await supabase
    .from('reports')
    .select('*, companies(name), profiles(full_name)')
    .eq('id', id)
    .single()

  if (error || !report) notFound()

  const aiOutput = report.ai_output as {
    executiveSummary?: string
    keyMetrics?: { label: string; value: string; trend: string; description: string }[]
    detailedAnalysis?: string
    trendsAndInsights?: string[]
    recommendations?: string[]
  } | null

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="sticky top-16 z-20 bg-background/80 backdrop-blur-sm border-b border-border/50 -mx-6 px-6 py-3 flex items-center justify-between">
        <Link href="/dashboard/reports">
          <Button variant="ghost" size="sm">
            <ArrowLeft size={16} className="mr-1" /> Back
          </Button>
        </Link>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" id="share-btn">
            <Share2 size={14} className="mr-1" /> Share
          </Button>
          <Button variant="outline" size="sm">
            <Download size={14} className="mr-1" /> Download PDF
          </Button>
        </div>
      </div>

      <Card className="p-8 md:p-12 border-border/50 shadow-none max-w-3xl mx-auto bg-background">
        <div className="text-center mb-10">
          <h1 className="text-3xl font-light mb-2">{(report.companies as { name?: string })?.name || 'Company'}</h1>
          <h2 className="text-xl font-medium mb-3">{report.title}</h2>
          <div className="flex items-center justify-center gap-3 text-sm text-muted-foreground">
            <Badge variant="outline">{reportTypeLabels[report.type as string] || report.type}</Badge>
            <span>{new Date(report.date_from || report.created_at).toLocaleDateString()} - {new Date(report.date_to || report.created_at).toLocaleDateString()}</span>
          </div>
          <p className="text-xs text-muted-foreground mt-4">Generated by Tigil Reports</p>
        </div>

        {aiOutput?.executiveSummary && (
          <div className="bg-surface rounded-lg border border-border/50 p-6 mb-8 italic text-muted-foreground">
            {aiOutput.executiveSummary}
          </div>
        )}

        {aiOutput?.keyMetrics && aiOutput.keyMetrics.length > 0 && (
          <div className="mb-8">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-4">Key Metrics</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {aiOutput.keyMetrics.map((metric, i) => (
                <Card key={i} className="p-4 border-border/50 shadow-none">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs text-muted-foreground">{metric.label}</span>
                    <TrendIcon trend={metric.trend} />
                  </div>
                  <div className="text-xl font-light">{metric.value}</div>
                  <p className="text-xs text-muted-foreground mt-1">{metric.description}</p>
                </Card>
              ))}
            </div>
          </div>
        )}

        {aiOutput?.detailedAnalysis && (
          <div className="mb-8">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-4">Detailed Analysis</h3>
            <div className="text-sm leading-relaxed space-y-3 text-muted-foreground">
              {aiOutput.detailedAnalysis.split('\n\n').map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>
          </div>
        )}

        {aiOutput?.trendsAndInsights && aiOutput.trendsAndInsights.length > 0 && (
          <div className="mb-8">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-4">Trends & Insights</h3>
            <ul className="space-y-2">
              {aiOutput.trendsAndInsights.map((insight, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  <CheckCircle size={16} className="text-green-500 mt-0.5 shrink-0" />
                  <span className="text-muted-foreground">{insight}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {aiOutput?.recommendations && aiOutput.recommendations.length > 0 && (
          <div>
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider mb-4">Recommendations</h3>
            <div className="space-y-3">
              {aiOutput.recommendations.map((rec, i) => (
                <div key={i} className="p-4 rounded-lg border border-border/50 flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full bg-foreground text-background text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  <span className="text-sm text-muted-foreground">{rec}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </Card>
    </div>
  )
}
